# Generated by Django 5.0.2 on 2025-05-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('signer', models.CharField(max_length=255)),
                ('recovery_signer', models.CharField(max_length=255)),
                ('helper', models.TextField()),
            ],
        ),
    ]
