services:
  db:
    image: postgres:latest
    command: postgres -c 'max_connections=200'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    restart: on-failure

  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    restart: on-failure

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 manage.py migrate; python3 manage.py push_config_redis; uvicorn core.asgi:application --port 8000 --host 0.0.0.0'
    volumes:
      - ./src/:/app/
    depends_on:
      - db
    restart: on-failure
    env_file:
      - .env
    ports:
      - "127.0.0.1:8081:8000"


volumes:
  postgresql-data:
  redis-data:
    external: false
